### ISSUE TITLE
Crash after leaving lobby (Local Match/Private)

### ISSUE THREAD

**Issue by clx127** [XLabsProject/iw6x-client#239]
Before new update i had a 1.0.3v and multiplayer with bots all was fine. Now when i downloaded 1.0.5.702v and after finishing match with bots, then leaving lobby game crashed with some fatal error messages. Here is dumps
[iw6x-crash-2-2020-12-09-03-56-59.zip](https://github.com/XLabsProject/iw6x-client/files/5662217/iw6x-crash-2-2020-12-09-03-56-59.zip)
[iw6x-crash-2-2020-12-09-03-57-04.zip](https://github.com/XLabsProject/iw6x-client/files/5662218/iw6x-crash-2-2020-12-09-03-57-04.zip)

**Comment by momo5502** [comment]
You are using a developer build. You are not supposed to do that. Grab a release build from here: https://downloads.xlabs.dev/iw6x.exe

**Comment by momo5502** [comment]
Crashes while executing emulated steam callbacks. Might be related to an ABI change within the compiler.

**Comment by momo5502** [comment]
Or I forgot to implement SteamAPI_UnregisterCallback...

**Comment by momo5502** [comment]
Should be fixed with this commit: 0cedff9016a4af9c37571ed29a4bd4e5d2a88b4b

**Comment by clx127** [comment]
> Should be fixed with this commit: [0cedff9](https://github.com/XLabsProject/iw6x-client/commit/0cedff9016a4af9c37571ed29a4bd4e5d2a88b4b)

So it's already was fixed? Yesterday i'm downloaded version of 1.0.5.695 and when i launch it shows me some error

**Comment by momo5502** [comment]
> > Should be fixed with this commit: [0cedff9](https://github.com/XLabsProject/iw6x-client/commit/0cedff9016a4af9c37571ed29a4bd4e5d2a88b4b)
> 
> So it's already was fixed? Yesterday i'm downloaded version of 1.0.5.695 and when i launch it shows me some error

No, I fixed it right now

**Comment by clx127** [comment]
> > > Should be fixed with this commit: [0cedff9](https://github.com/XLabsProject/iw6x-client/commit/0cedff9016a4af9c37571ed29a4bd4e5d2a88b4b)
> > 
> > 
> > So it's already was fixed? Yesterday i'm downloaded version of 1.0.5.695 and when i launch it shows me some error
> 
> No, I fixed it right now

Weird. Im redownloaded  release build that you posted above. And when i launch it still shows me that error
![bandicam_2020-12-09_03-32-30-261](https://user-images.githubusercontent.com/75702180/101628446-03c27a80-3a4a-11eb-8256-02102c6af617.jpg)

**Comment by clx127** [comment]
Previusly i have a 1.0.3v and all was fine, and when i manually updated to latest version and i get this error... But with version 1.0.5.702 was fine

**Comment by clx127** [comment]
> > > Should be fixed with this commit: [0cedff9](https://github.com/XLabsProject/iw6x-client/commit/0cedff9016a4af9c37571ed29a4bd4e5d2a88b4b)
> > 
> > 
> > So it's already was fixed? Yesterday i'm downloaded version of 1.0.5.695 and when i launch it shows me some error
> 
> No, I fixed it right now

?

**Comment by clx127** [comment]
That new released version of 1.0.5 crashes when launching

**Comment by momo5502** [comment]
The release binary only works on Windows 10, due to the bug you already saw. It has bin fixed yesterday, but obviously it has not been released yet. You can alternatively grab the develop binary again. You can find it in the readme.

**Comment by momo5502** [comment]
Please commit if the bug was fixed!
Or here: https://ci.appveyor.com/api/projects/XLabsProject/iw6x-client/artifacts/build%2Fbin%2Fx64%2FRelease%2Fiw6x.exe?branch=develop&job=Environment%3A%20APPVEYOR_BUILD_WORKER_IMAGE%3DVisual%20Studio%202019%2C%20PREMAKE_ACTION%3Dvs2019%2C%20CI%3D1%3B%20Configuration%3A%20Release

**Comment by clx127** [comment]
> Please commit if the bug was fixed!
> Get the dev build from here: https://ci.appveyor.com/api/projects/XLabsProject/iw6x-client/artifacts/build%2Fbin%2Fx64%2FRelease%2Fiw6x.exe?branch=develop&job=Environment%3A%20APPVEYOR_BUILD_WORKER_IMAGE%3DVisual%20Studio%202019%2C%20PREMAKE_ACTION%3Dvs2019%2C%20CI%3D1%3B%20Configuration%3A%20Release

Yes, now it works fine! Can you release this version?:)

**Comment by momo5502** [comment]
> > Please commit if the bug was fixed!
> > Get the dev build from here: https://ci.appveyor.com/api/projects/XLabsProject/iw6x-client/artifacts/build%2Fbin%2Fx64%2FRelease%2Fiw6x.exe?branch=develop&job=Environment%3A%20APPVEYOR_BUILD_WORKER_IMAGE%3DVisual%20Studio%202019%2C%20PREMAKE_ACTION%3Dvs2019%2C%20CI%3D1%3B%20Configuration%3A%20Release
> 
> Yes, now it works fine! Can you pls release this version?:)

Not yet, no.

**Comment by clx127** [comment]
> > > Please commit if the bug was fixed!
> > > Get the dev build from here: https://ci.appveyor.com/api/projects/XLabsProject/iw6x-client/artifacts/build%2Fbin%2Fx64%2FRelease%2Fiw6x.exe?branch=develop&job=Environment%3A%20APPVEYOR_BUILD_WORKER_IMAGE%3DVisual%20Studio%202019%2C%20PREMAKE_ACTION%3Dvs2019%2C%20CI%3D1%3B%20Configuration%3A%20Release
> > 
> > 
> > Yes, now it works fine! Can you pls release this version?:)
> 
> Not yet, no.

About relesaed version and develop build version are same?
